trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: '3.x'
    includePreviewVersions: true

- script: dotnet build --configuration Release
  displayName: 'Build Application'

- script: dotnet test --configuration Release
  displayName: 'Run Tests'

- script: dotnet publish --configuration Release
  displayName: 'Publish Application Artifacts'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/<PathToPublish>'
    ArtifactName: 'drop'
    publishLocation: 'container'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    testType: 'app'
    severityThreshold: 'high'
    monitorWhen: 'always'
    failOnIssues: true