trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
  workingDirectory: 'arnebjerke'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'SnykUsedforPipelinePurposes'
    testType: 'app'
    severityThreshold: 'high'
    monitorWhen: 'always'
    failOnIssues: true